name: flu_ar_simple
description: AR Camera Application
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # CamÃ©ra et permissions
  camera: ^0.10.5+5
  permission_handler: ^11.3.1
  
  # Stockage et fichiers
  path_provider: ^2.1.1
  path: ^1.8.3
  gal: ^2.3.0
  
  # Screenshot
  screenshot: ^3.0.0
  
  # 3D Model Viewer (pour GLB futur)
  model_viewer_plus: ^1.7.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/models/
    - assets/images/